[package]
name = "ShardEngine"
version = "0.1.0"
authors = ["Bernhard Miettinen <bernhard.miettinen@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"

sdl2 = {version = "0.31.0", features = ["bundled", "static-link"]}
gl = "0.10.0"